// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uafogqdrmzgllystrkkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZm9ncWRybXpnbGx5c3Rya2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NTQ4MTUsImV4cCI6MjA3NDEzMDgxNX0.Z2M6PDaycFxgMVwyKnbNlwS9NZVVCdN8pZgr246iQkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});